# Generated by Django 5.0.6 on 2024-08-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
